In [1]:
# Creating a 1D NumPy array
import numpy as np
arr1 = np.array([10, 20, 30, 40, 50])

print("1D Array:", arr1)

1D Array: [10 20 30 40 50]


In [2]:
# Creating a 2D NumPy array
arr2 = np.array([[10, 20, 30],
                 [40, 50, 60]])

print("2D Array:")
print(arr2)

2D Array:
[[10 20 30]
 [40 50 60]]


In [3]:
arr = np.array([10, 20, 30, 40, 50])

print("First element:", arr[0])
print("Third element:", arr[2])
print("Last element:", arr[-1])

First element: 10
Third element: 30
Last element: 50


In [4]:
arr2 = np.array([[10, 20, 30],
                 [40, 50, 60]])

print("Element at row 1, column 2:", arr2[0, 1])
print("Element at row 2, column 3:", arr2[1, 2])

Element at row 1, column 2: 20
Element at row 2, column 3: 60


In [5]:
arr = np.array([10, 20, 30, 40, 50])

print("First three elements:", arr[0:3])
print("Elements from index 2:", arr[2:])
print("Every second element:", arr[::2])

First three elements: [10 20 30]
Elements from index 2: [30 40 50]
Every second element: [10 30 50]


In [6]:
arr2 = np.array([[10, 20, 30],
                 [40, 50, 60]])

print("First row:", arr2[0, :])
print("First two columns:")
print(arr2[0:1, :])

First row: [10 20 30]
First two columns:
[[10 20]
 [40 50]]


In [7]:
arr1 = np.array([10, 20, 30, 40, 50])

arr2 = np.array([[10, 20, 30],
                 [40, 50, 60]])

print("1D Array Shape:", arr1.shape)
print("1D Array Dimensions:", arr1.ndim)

print("2D Array Shape:", arr2.shape)
print("2D Array Dimensions:", arr2.ndim)

1D Array Shape: (5,)
1D Array Dimensions: 1
2D Array Shape: (2, 3)
2D Array Dimensions: 2


In [8]:
arr = np.array([10, 20, 30, 40, 50])

print("Addition:", arr + 5)
print("Subtraction:", arr - 5)
print("Multiplication:", arr * 2)
print("Division:", arr / 2)

Addition: [15 25 35 45 55]
Subtraction: [ 5 15 25 35 45]
Multiplication: [ 20  40  60  80 100]
Division: [ 5. 10. 15. 20. 25.]


In [9]:
arr = np.array([10, 20, 30, 40, 50])

print("Mean:", np.mean(arr))
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))
print("Sum:", np.sum(arr))

Mean: 30.0
Maximum: 50
Minimum: 10
Sum: 150


In [10]:
import numpy as np

accuracy = np.array([82, 85, 88, 90, 87])

print("AI Model Accuracy:", accuracy)

print("Average Accuracy:", np.mean(accuracy))
print("Highest Accuracy:", np.max(accuracy))
print("Lowest Accuracy:", np.min(accuracy))
print("Total:", np.sum(accuracy))

AI Model Accuracy: [82 85 88 90 87]
Average Accuracy: 86.4
Highest Accuracy: 90
Lowest Accuracy: 82
Total: 432
