In [1]:
import os
import warnings

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"
warnings.filterwarnings("ignore")

import numpy as np
import tensorflow as tf

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# For reproducible results
np.random.seed(42)
tf.random.set_seed(42)

print("Libraries imported successfully.")

Libraries imported successfully.


In [2]:
# Load Iris dataset
iris = load_iris()

# Features and target
X = iris.data
y = iris.target

print("Dataset loaded successfully.")
print("Dataset shape:", X.shape)
print("Feature names:", iris.feature_names)
print("Target classes:", iris.target_names)

Dataset loaded successfully.
Dataset shape: (150, 4)
Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target classes: ['setosa' 'versicolor' 'virginica']


In [3]:
print("First 5 feature records:")
print(X[:5])

print("\nFirst 5 target values:")
print(y[:5])

First 5 feature records:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

First 5 target values:
[0 0 0 0 0]


In [4]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training feature shape:", X_train.shape)
print("Testing feature shape:", X_test.shape)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

Training feature shape: (120, 4)
Testing feature shape: (30, 4)
Training samples: 120
Testing samples: 30


In [5]:
scaler = StandardScaler()

# Learn scaling only from training data
X_train = scaler.fit_transform(X_train)

# Apply the same scaling to test data
X_test = scaler.transform(X_test)

print("Data preprocessing completed.")
print("\nFirst 5 scaled training samples:")
print(X_train[:5])

Data preprocessing completed.

First 5 scaled training samples:
[[-1.72156775 -0.33210111 -1.34572231 -1.32327558]
 [-1.12449223 -1.22765467  0.41450518  0.6517626 ]
 [ 1.14439475 -0.5559895   0.58484978  0.25675496]
 [-1.12449223  0.11567567 -1.28894078 -1.45494479]
 [-0.40800161 -1.22765467  0.13059752  0.12508575]]


In [6]:
model = tf.keras.Sequential([

    # Input layer: 4 Iris features
    tf.keras.layers.Input(shape=(4,)),

    # First hidden layer
    tf.keras.layers.Dense(
        units=16,
        activation="relu"
    ),

    # Second hidden layer
    tf.keras.layers.Dense(
        units=8,
        activation="relu"
    ),

    # Output layer: 3 flower classes
    tf.keras.layers.Dense(
        units=3,
        activation="softmax"
    )
])

print("Neural network created successfully.")

Neural network created successfully.


In [7]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 16)             │            80 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 3)              │            27 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 243 (972.00 B)

 Trainable params: 243 (972.00 B)

 Non-trainable params: 0 (0.00 B)

In [8]:
model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

print("Model compiled successfully.")

Model compiled successfully.


In [9]:
history = model.fit(
    X_train,
    y_train,
    epochs=50,
    batch_size=8,
    validation_split=0.20,
    verbose=1
)

Epoch 1/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 46ms/step - accuracy: 0.5729 - loss: 0.9536 - val_accuracy: 0.5833 - val_loss: 0.9433
Epoch 2/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.5833 - loss: 0.8875 - val_accuracy: 0.6250 - val_loss: 0.8849
Epoch 3/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6875 - loss: 0.8264 - val_accuracy: 0.6667 - val_loss: 0.8302
Epoch 4/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6979 - loss: 0.7700 - val_accuracy: 0.6667 - val_loss: 0.7804
Epoch 5/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7188 - loss: 0.7173 - val_accuracy: 0.6667 - val_loss: 0.7374
Epoch 6/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7917 - loss: 0.6693 - val_accuracy: 0.6667 - val_loss: 0.6980
Epoch 7/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8021 - loss: 0.6261 - val_accuracy: 0.6667 - val_loss: 0.6632
Epoch 8/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.8333 - loss: 0.5877 - val_accuracy: 0.7083 - v